spring:
  session:
    store-type: none
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://xxx/redo-test?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
    druid:
      initial-size: 8
      max-active: 64
      max-pool-prepared-statement-per-connection-size: 20
      max-wait: 60000
      min-evictable-idle-time-millis: 300000
      min-idle: 8
      pool-prepared-statements: false
      remove-abandoned: true
      remove-abandoned-timeout: 1800
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      validation-query: select 'x'
threadpool:
  corePoolSize: 8
  maxPoolSize: 16
  queueCapacity: 200
  keepAliveSeconds: 3000